# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
PackageIdentifier: 'Komput.Komput'
PackageVersion: '0.3.9-beta.24'
InstallerType: exe
Scope: user
InstallModes:
  - silent
  - silentWithProgress
  - interactive
UpgradeBehavior: install
InstallerSwitches:
  Silent: '/silent'
  SilentWithProgress: '/silent'
  Interactive: '/interactive'
Installers:
  - Architecture: x64
    InstallerUrl: 'https://github.com/keremerdogdu92/Komput-Releases/releases/download/v0.3.9-beta.24/Komput-Setup-0.3.9-beta.24.exe'
    InstallerSha256: 56FABD22CAD2A71E34B08DFA062950DC00F96580D7A802C0C2D2EC1925B31F4F
    AppsAndFeaturesEntries:
      - DisplayName: 'Komput'
        Publisher: 'Komput'
ManifestType: installer
ManifestVersion: 1.12.0
